### ISSUE TITLE
Update colormap of map when zoom

### ISSUE THREAD

**Issue by WesleyTheGeolien** [CEREGE-CL/netcdf_editor_app#11]
It would be good if when we decide to zoom in the colormap updates automatically to reflect the value range of the data currently in view.

Extension of #4

**Comment by jbladant** [comment]
I add this here because it relates to colormaps:
In my browser, the mask function works well but the colormap does funny things. Let's say I define a colormap (without the mask function). When I apply the mask function with variable cutoff values, the colormap changes from the original choice. If I put a cutoff value of 0 or 1, I get a colored map that is different from the gray/black colormap that you get at larger cutoff values. I guess this is related to the scale that adapt to the cutoff values. What would be ideal is that if your original topo is between 0 and 2500 m, if you mask values below 1000 m, the scale becomes 1000 - 2500 m rather than being centered on 1000 m (right now it displays 999 - 1001 m).

**Comment by WesleyTheGeolien** [comment]
> I add this here because it relates to colormaps:
> In my browser, the mask function works well but the colormap does funny things. Let's say I define a colormap (without the mask function). When I apply the mask function with variable cutoff values, the colormap changes from the original choice. If I put a cutoff value of 0 or 1, I get a colored map that is different from the gray/black colormap that you get at larger cutoff values. I guess this is related to the scale that adapt to the cutoff values. What would be ideal is that if your original topo is between 0 and 2500 m, if you mask values below 1000 m, the scale becomes 1000 - 2500 m rather than being centered on 1000 m (right now it displays 999 - 1001 m).

@jbladant This function was introduced after talking to Yannick Donnadieu, he wanted an easy way to find inland oceans (values below 0 inside continents).

To still have access to the underlying values of the variable the "mask" is in reality just a transform of the colormap to the value set in the _mask value_ spinner. I have set by default values at the bottom to be grey and values above to be black (this can be easily modified if the color scheme is inappropriate. Unfortunately (is this a problem??) The locations where the value is the mask value (or close -+1 as you point out) are still colored with the original colormap
