### ISSUE TITLE
Lasso select does not select

### ISSUE THREAD

**Issue by psepulchre** [CEREGE-CL/netcdf_editor_app#93]
**Describe the bug**
Cannot make the lasso selection tool work.
The lasso appears, but selection is not made.

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6 (!)
 - Browser : Firefox 85.0

**Additional context**
App run from Docker Desktop 3.0.0

**Comment by WesleyTheGeolien** [comment]
Thanks for catching this @psepulchre I have just checked locally and it looks like `data shader` is not inside the docker container.

I am fixing for this: `holoviews.core.options.CallbackError: linked_selection aborted because it could not display selection for all elements: Lasso selection on gridded data requires datashader to be available..` could you please confirm you see this inside your console?

**Comment by psepulchre** [comment]
I confirm.

**Comment by WesleyTheGeolien** [comment]
Thanks @psepulchre I have pushed a fix to the repo which will trigger a new docker hub build
